# Generated by Django 5.2.6 on 2026-04-25 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0002_userprofile_github_url_userprofile_leetcode_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_cover',
            field=models.ImageField(blank=True, default='default/bg.jpg', upload_to='users/bg_image/'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, default='default/profile-pic.webp', null=True, upload_to='users/profile_pictures/'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='users/resumes/'),
        ),
    ]
