# Generated by Django 5.2.6 on 2025-11-12 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chats", "0003_groupemembers"),
    ]

    operations = [
        migrations.AddField(
            model_name="groupeschat",
            name="private",
            field=models.BooleanField(default=False),
        ),
    ]
