# Generated by Django 5.2.6 on 2026-03-23 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Notifictions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='body',
        ),
    ]
