# Generated by Django 5.2.6 on 2025-11-12 13:02

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chats", "0004_groupeschat_private"),
    ]

    operations = [
        migrations.AddField(
            model_name="groupeschat",
            name="groupe_link",
            field=models.URLField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name="groupeschat",
            name="qr_code",
            field=models.ImageField(
                blank=True, null=True, upload_to="groupes_qr_codes/"
            ),
        ),
    ]
