# Generated by Django 5.2.6 on 2025-11-12 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("complains", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="complain",
            name="room_number",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
