# Generated by Django 5.2.6 on 2026-04-01 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='github_url',
            field=models.URLField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='leetcode_url',
            field=models.URLField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='linkedin_url',
            field=models.URLField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='profile_cover',
            field=models.ImageField(blank=True, upload_to='bg_image'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='resumes/'),
        ),
    ]
